team_builder/accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('signin/', views.LoginView.as_view(), name='signin'),
    path('signout/', views.LogoutView.as_view(), name='signout'),
    path('<pk>/', views.profile_detail, name='profile'),
    path('<pk>/edit', views.profile_edit, name='edit'),
]

team_builder/projects/urls.py
from django.urls import path

from . import views

app_name='projects'

urlpatterns = [
	path('create/', views.create_project, name='create'),
	path('notification/', views.notification, name='notification'),
	path('application/', views.application_list, name='application'),
    path('application/<pk>/accept/', views.accept_application, name="accept"),
    path('application/<pk>/reject/', views.reject_application, name="reject"),
    path('application/accept/', views.accept_application_list, name="accept_application"),
    path('application/reject/', views.reject_application_list, name="reject_application"),
    path('application/new/', views.new_application_list, name="new_application"),
	path('<pk>/', views.project_detail, name='project'),
	path('edit/<pk>/', views.edit_project, name='edit'),
	path('<pk>/delete/', views.delete_project, name='delete'),
	path('<pk>/apply/<position_pk>', views.apply, name='apply'),
]

team_builder/team_builder/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import views


urlpatterns = [
	path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('projects/', include(('projects.urls', 'projects'), namespace='projects')),
    path('profile/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('search/', views.search_term, name='search'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

team_builder/templates/index.html
{% extends 'layout.html' %}

{% block content %}
<div class="bounds circle--page">
  <div class="circle--page--header circle--fluid">
    <div class="circle--fluid--cell circle--fluid--primary">
      <h2>Projects</h2>
    </div>
    <div class="circle--fluid--cell circle--fluid--secondary">
      {% if user.is_authenticated %}
      <a class="button button-primary icon-on-left" href="{% url 'projects:create' %}">
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 13 13" style="enable-background:new 0 0 13 13;" xml:space="preserve" class="add">
          <polygon points="7,6 7,0 6,0 6,6 0,6 0,7 6,7 6,13 7,13 7,7 13,7 13,6 "/>
        </svg>
        New Project
      </a>
      {% else %}
      <a class="button button-primary icon-on-left" href="{% url 'accounts:signin' %}">
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 13 13" style="enable-background:new 0 0 13 13;" xml:space="preserve" class="add">
          <polygon points="7,6 7,0 6,0 6,6 0,6 0,7 6,7 6,13 7,13 7,7 13,7 13,6 "/>
        </svg>
        New Project
      </a>
      {% endif %}
    </div>
  </div>

  <div class="grid-25">
    <div class="circle--filter circle--secondary--module">
      <h4>Project Needs</h4>
      <ul class="circle--filter--list">
        <li><a class="selected">All Needs</a></li>
          {% for project in projects %}
            {% for position in project.positions.all %}
              {% if position.position_filled != True %}
                <li><a href={% url 'projects:project' pk=project.pk %}>{{ position.skill }}</a></li>
              {% endif %}
            {% endfor %}
          {% endfor %}
      </ul>
    </div>
  </div>

  <div class="grid-70 grid-push-5">
    <table class="u-full-width circle--table">
      <thead>
        <tr>
          <th>Project Title</th>
          <th class="circle--cell--right">Project Needs</th>
        </tr>
      </thead>
      <tbody>
        {% for project in projects %}
        <tr class="clickable-row" data-href="{% url 'projects:project' project.id %}">
          <td>
            <h3>{{ project.name }}</h3>
          </td>
          <td class="circle--cell--right">
            {% for position in project.positions.all %}
            {% if position.position_filled != True %}
              <p class="secondary-label">{{ position.skill }}</p>
            {% endif %}
            {% endfor %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

team_builder/templates/layout.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>{% block title %}Circle{% endblock %}</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONTS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href={% static "css/global.css" %}>

  <!-- JS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
  <script type="text/javascript" src={% static "js/autogrow.js" %}></script>
  <script type="text/javascript" src={% static "js/global.js" %}></script>


</head>
<body>
  <header class="circle--header">
    <div class="bounds">
      <div class="circle--fluid">
        <div class="circle--fluid--cell">
          <h1 class="hide-text circle--logo"><a class="logo" href="{% url 'home' %}">Circle</a></h1>
        </div>
        <div class="circle--fluid--cell circle--fluid--primary">
          <div class="circle--search">
            <form action="{% url 'search' %}" method="GET">
              <input type='search' name='q'><button type='button' class='secondary small button'>
                <svg version="1.1" class="search" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 12 12" xml:space="preserve">
                  <path d="M12,10.6L8.3,6.9C8.7,6.2,9,5.4,9,4.5C9,2,7,0,4.5,0S0,2,0,4.5S2,9,4.5,9c0.9,0,1.7-0.3,2.4-0.7l3.7,3.7L12,10.6z M2,4.5
                  C2,3.1,3.1,2,4.5,2S7,3.1,7,4.5C7,5.9,5.9,7,4.5,7S2,5.9,2,4.5z"/>
                </svg>
            </form>
          </div>
        </div>
        <div class="circle--fluid--cell circle--fluid--secondary">
          <nav>
            <ul class="circle--inline">
              {% if user.is_authenticated %}
              <li><a href="{% url 'accounts:profile' user.id %}">{{ user.username }}</a></li>
              <li><a href="{% url 'accounts:signout' %}">Sign Out</a></li>
              {% else %}
              <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
              <li><a href="{% url 'accounts:signin' %}">Sign In</a></li>
              {% endif %}
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </header>
{% block content %}
{% endblock %}
</body>
</html>