team_builder/accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('signin/', views.LoginView.as_view(), name='signin'),
    path('signout/', views.LogoutView.as_view(), name='signout'),
    path('<pk>/', views.profile_detail, name='profile'),
    path('<pk>/edit', views.profile_edit, name='edit'),
]

team_builder/projects/urls.py
from django.urls import path

from . import views

app_name='projects'

urlpatterns = [
	path('create/', views.create_project, name='create'),
	path('notification/', views.notification, name='notification'),
	path('application/', views.application_list, name='application'),
    path('application/<pk>/accept/', views.accept_application, name="accept"),
    path('application/<pk>/reject/', views.reject_application, name="reject"),
    path('application/accept/', views.accept_application_list, name="accept_application"),
    path('application/reject/', views.reject_application_list, name="reject_application"),
    path('application/new/', views.new_application_list, name="new_application"),
	path('<pk>/', views.project_detail, name='project'),
	path('edit/<pk>/', views.edit_project, name='edit'),
	path('<pk>/delete/', views.delete_project, name='delete'),
	path('<pk>/apply/<position_pk>', views.apply, name='apply'),
]

team_builder/team_builder/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import views


urlpatterns = [
	path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('projects/', include(('projects.urls', 'projects'), namespace='projects')),
    path('profile/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('search/', views.search_term, name='search'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

team_builder/accounts/models.py
from django.conf import settings
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin
)
from django.urls import reverse, reverse_lazy
from django.db import models
from django.utils import timezone

# Create your models here.
class UserManager(BaseUserManager):
    def create_user(self, username, email, password=None):
        if not email:
            raise ValueError("Users must have an email address.")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, username, email, password):
        user = self.create_user(
            username,
            email,
            password
        )
        user.is_staff = True
        user.is_superuser = True
        user.save()
        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=40, unique=True)
    name = models.CharField(max_length=100, default='')
    bio = models.TextField(max_length=500, blank=True, default='')
    image = models.ImageField(upload_to="profile_image/", blank=True)
    date_joined = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)


    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    def __str__(self):
        return self.username

    def get_short_name(self):
        return self.username


ANDROID = "Android"
DESIGN = "Design"
JAVA = "Java"
PHP = "PHP"
PYTHON = "Python"
RAILS = "Rails"
WORDPRESS = "Wordpress"
iOS = "iOS"
SKILLES_CHOICES = (
    (ANDROID, "Android"),
    (DESIGN, "Design"),
    (JAVA, "Java"),
    (PHP, "PHP"),
    (PYTHON, "Python"),
    (RAILS, "Rails"),
    (WORDPRESS, "Wordpress"),
    (iOS, "iOS")
)

class Skill(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=20, choices=SKILLES_CHOICES)

team_builder/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


from . import models


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["email"].label = "Email address"


class ProfileForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ('name', 'image', 'bio')


class SkillForm(forms.ModelForm):
    class Meta:
        model = models.Skill
        fields = ('name',)


SkillFormSet = forms.modelformset_factory(
    models.Skill,
    form=SkillForm,
)

SkillInlineFormSet = forms.inlineformset_factory(
    models.User,
    models.Skill,
    extra=3,
    fields=('name', ),
    formset=SkillFormSet,
    min_num=1,
    can_delete=True,
)

team_builder/accounts/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.views import generic
from PIL import Image

from projects.models import Position, Project, Application
from . import forms
from . import models


class LoginView(generic.FormView):
    form_class = AuthenticationForm
    success_url = reverse_lazy('home')
    template_name = 'accounts/signin.html'

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(self.request, **self.get_form_kwargs())

    def form_valid(self, form):
       login(self.request, form.get_user())
       return super().form_valid(form)


class LogoutView(generic.RedirectView):
    url = reverse_lazy('home')

    def get(self, request, *args, **kwargs):
        logout(request)
        return super().get(request, *args, **kwargs)


class SignUp(generic.CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('accounts:signin')
    template_name = 'accounts/signup.html'


@login_required
def profile_edit(request, pk):
    '''Update user profile.'''
    profile = get_object_or_404(models.User, id=pk)
    form = forms.ProfileForm(instance=profile)
    skill_formset = forms.SkillInlineFormSet(
        queryset=models.Skill.objects.filter(user_id=pk)
    )
    if request.method == 'POST':
        form = forms.ProfileForm(request.POST, request.FILES, instance=profile)
        skill_formset = forms.SkillInlineFormSet(
            request.POST,
            queryset=models.Skill.objects.filter(user_id=pk)
            )

        if form.is_valid() and skill_formset.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            skill_instance = skill_formset.save(commit=False)
            for obj in skill_formset.deleted_objects:
                obj.delete()
            for skill in skill_instance:
                skill.user=request.user
                skill.save()
            return redirect('accounts:profile', pk=request.user.id)

    return render(request, 'accounts/profile_edit.html', {
                'form': form,
                'skill_formset': skill_formset })


@login_required
def profile_detail(request, pk):
    profile = get_object_or_404(models.User, pk=pk)
    skills = models.Skill.objects.filter(user_id=pk)
    projects = Project.objects.filter(user_id=pk)
    applications = Application.objects.filter(
                        applicant=request.user,
                        status='accept')
    return render(request, 'accounts/profile.html', {'pk': pk,
            'profile': profile,
            'skills': skills,
            'projects': projects ,
            'applications': applications })

team_builder/accounts/templates/accounts/applications.html
{% extends 'accounts/layout.html' %}

{% block title %}Applications | {{ block.super }}{% endblock %}

{% block content %}
  <div class="bounds circle--page">
    <div class="circle--page--header grid-100">
      <h2>Applications</h2>
    </div>

    <div class="grid-25">
      <div class="circle--filter circle--secondary--module">
        <h4>Status</h4>
        <ul class="circle--filter--list">
          {% if 'accept' in request.path %}
          <li><a href="{% url 'projects:application' %}">All Applications</a></li>
          <li><a href="{% url 'projects:new_application' %}">New Applications</a></li>
          <li><a class="selected" href="{% url 'projects:accept_application' %}">Accepted</a></li>
          <li><a href="{% url 'projects:reject_application' %}">Rejected</a></li>
          {% elif 'reject' in request.path %}
          <li><a href="{% url 'projects:application' %}">All Applications</a></li>
          <li><a href="{% url 'projects:new_application' %}">New Applications</a></li>
          <li><a href="{% url 'projects:accept_application' %}">Accepted</a></li>
          <li><a class="selected" href="{% url 'projects:reject_application' %}">Rejected</a></li>
          {% elif 'new' in request.path %}
          <li><a href="{% url 'projects:application' %}">All Applications</a></li>
          <li><a class="selected" href="{% url 'projects:new_application' %}">New Applications</a></li>
          <li><a href="{% url 'projects:accept_application' %}">Accepted</a></li>
          <li><a href="{% url 'projects:reject_application' %}">Rejected</a></li>
          {% else %}
          <li><a class="selected" href="{% url 'projects:application' %}">All Applications</a></li>
          <li><a href="{% url 'projects:new_application' %}">New Applications</a></li>
          <li><a href="{% url 'projects:accept_application' %}">Accepted</a></li>
          <li><a href="{% url 'projects:reject_application' %}">Rejected</a></li>
          {% endif %}
        </ul>
      </div>

      <div class="circle--filter circle--secondary--module">
        <h4>My Projects</h4>
        <ul class="circle--filter--list">
          <li><a class="selected">All Projects</a></li>
          {% for project in projects %}
            <li><a href="{% url 'projects:project' pk=project.pk %}">{{ project.name }}</a></li>
          {% endfor %}
        </ul>
      </div>

      <div class="circle--filter circle--secondary--module">
        <h4>Project Needs</h4>
        <ul class="circle--filter--list">
          <li><a class="selected">All Needs</a></li>
            {% for project in projects %}
              {% for position in project.positions.all %}
                <li><a href="{% url 'projects:project' pk=position.project.pk %}">{{ position.skill }}</a></li>
              {% endfor %}
            {% endfor %}
        </ul>
      </div>

    </div>

    <div class="grid-70 grid-push-5">
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Applicant</th>
            <th class="circle--cell--right">Applicant Position</th>
          </tr>
        </thead>
        <tbody>
          {% for application in applications %}
            {% if application.applicant != request.user %}
              <tr class="clickable-row" data-href="{% url "accounts:profile" pk=application.applicant.pk %}">
                <td>
                  <h3>{{ application.applicant }}</h3>
                  <p>{{ application.position.project.name }}</p>
                </td>
                <td class="circle--cell--right">
                  <span class="secondary-label">{{ application.position.title }}</span>
                </td>
                <td>
                  {% if application.status == "new" %}
                    <a class="button button-primary" href="{% url 'projects:accept' pk=application.pk %}">Accept</a>
                  {% endif %}
                  {% if application.status == "accept" %}
                    <a class="button button-primary button-inactive">Accepted</a>
                  {% elif application.status == "reject" %}
                    <a class="button button-primary button-inactive">Rejected</a>
                  {% else %}
                    <a class="button button-primary" href="{% url 'projects:reject' pk=application.pk %}">Reject</a>
                  {% endif %}
                </td>
              </tr>
            {% endif %}
          {% endfor %}
        </tbody>
      </table>

    </div>
{% endblock %}

team_builder/accounts/templates/accounts/layout.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>{% block title %}Circle{% endblock %}</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONTS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href={% static "css/global.css" %}>

  <!-- JS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
  <script type="text/javascript" src={% static "js/autogrow.js" %}></script>
  <script type="text/javascript" src={% static "js/global.js" %}></script>


</head>
<body>
  <header class="circle--header">
    <div class="bounds">
      <div class="circle--fluid">
        <div class="circle--fluid--cell">
          <h1 class="hide-text circle--logo"><a class="logo" href="{% url 'home' %}">Circle</a></h1>
        </div>
        <div class="circle--fluid--cell circle--fluid--primary">
          <div class="circle--search">
            <form action="{% url 'search' %}" method="GET">
              <input type='search' name='q'><button type='button' class='secondary small button'>
                <svg version="1.1" class="search" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 12 12" xml:space="preserve">
                  <path d="M12,10.6L8.3,6.9C8.7,6.2,9,5.4,9,4.5C9,2,7,0,4.5,0S0,2,0,4.5S2,9,4.5,9c0.9,0,1.7-0.3,2.4-0.7l3.7,3.7L12,10.6z M2,4.5
                  C2,3.1,3.1,2,4.5,2S7,3.1,7,4.5C7,5.9,5.9,7,4.5,7S2,5.9,2,4.5z"/>
                </svg>
            </form>
          </div>
        </div>
        <div class="circle--fluid--cell circle--fluid--secondary">
          <nav>
            <ul class="circle--inline">
              {% if user.is_authenticated %}
              <li><a href="{% url 'accounts:profile' user.id %}">{{ user.username }}</a></li>
              <li><a href="{% url 'accounts:signout' %}">Sign Out</a></li>
              {% else %}
              <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
              <li><a href="{% url 'accounts:signin' %}">Sign In</a></li>
              {% endif %}
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </header>

  <div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
        {% if 'profile' in request.path %}
          <li><a href="{% url 'projects:application' %}">Applications</a></li>
          <li><a class="selected" href="{% url 'accounts:profile' user.id %}">Profile</a></li>
          <li><a href="{% url 'projects:notification' %}">Notifications</a></li>
        {% elif 'application' in request.path %}
          <li><a class="selected" href="{% url 'projects:application' %}">Applications</a></li>
          <li><a href="{% url 'accounts:profile' user.id %}">Profile</a></li>
          <li><a href="{% url 'projects:notification' %}">Notifications</a></li>
        {% else %}
        <li><a href="{% url 'projects:application' %}">Applications</a></li>
        <li><a href="{% url 'accounts:profile' user.id %}">Profile</a></li>
        <li><a class="selected" href="{% url 'projects:notification' %}">Notifications</a></li>
        {% endif %}
      </ul>
    </nav>
  </div>

{% block content %}
{% endblock %}
</body>
</html>

team_builder/accounts/templates/accounts/profile.html
{% extends 'accounts/layout.html' %}
{% load static from staticfiles %}
{% load project_extras %}

{% block title %}{{ user.name }}'s' Profile | {{ block.super }}{% endblock %}

{% block content %}
  <div class="bounds circle--page">
    <div class="circle--page--header circle--fluid">
        <div class="circle--fluid--cell circle--fluid--primary">
            <h2>Profile</h2>
        </div>
        {% if profile.id == request.user.id %}
            <div class="circle--fluid--cell circle--fluid--secondary">
                <a class="button icon-on-left" href="{% url 'accounts:edit' user.id %}">Edit</a>
            </div>
        {% endif %}
    </div>

    <div class="grid-70">
        <div class="circle--article--body">
              <h1>{{ profile.name }}</h1>
              {{ profile.bio | markdown_to_html }}
        </div>

        <h2>Past Projects</h2>
        <table class="u-full-width circle--table">
            <thead>
                <tr>
                    <th>Project Title</th>
                    <th class="circle--cell--right">Project Needs</th>
                </tr>
            </thead>
            <tbody>
                {% for application in applications %}
                    <tr class="clickable-row" data-href="{% url 'projects:project' pk=application.position.project.pk %}">
                        <td>
                            <h3>{{ application.position.project.name }}</h3>
                        </td>
                        <td class="circle--cell--right">
                            <span class="secondary-label">{{ application.position.skill }}</sapn>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="grid-25 grid-push-5">
        <div class="circle--secondary--module">
            <div class="circle--primary--avatar">
                {% if profile.image %}
                    <img src="{{ profile.image.url }}" height=200 width=200 alt="profile image"/>
                {% endif %}
            </div>
        </div>

        <div class="circle--secondary--module">
            <h4>My Skills</h4>
            <ul class="unloaded">
                {% for skill in skills %}
                <li>{{ skill.name }}</li>
                {% endfor %}
            </ul>


            <h4>My Projects</h4>
            <ul class="circle--link--list">
                {% for project in projects %}
                <li><a href="{% url 'projects:project' pk=project.pk %}">{{ project.name }}</a></li>
                {% endfor %}
            </ul>

        </div>

    </div>
</div>
{% endblock %}

team_builder/accounts/templates/accounts/profile_edit.html
{% extends 'layout.html' %}

{% block title %}Edit Profile | {{ block.super }}{% endblock %}

{% block content %}
<form method='POST' enctype="multipart/form-data">
  <div class="bounds circle--page">
    <div class="circle--page--header circle--fluid">
      <div class="circle--fluid--cell circle--fluid--primary">
        <h2>Profile</h2>
      </div>
      <div class="circle--fluid--cell circle--fluid--secondary">
        <input type="submit" value="Save changes" class="button button-primary icon-on-left">
      </div>
    </div>

    <div class="grid-70">
      <div type="text" placeholder="Full Name" class="circle--input--h1">
        Name:
        {% csrf_token %}
        {{ form.name }}
      </div>
      <div class="circle--article--body">
          Bio:
          {{ form.bio }}
      </div>

      <h2>Past Projects</h2>
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Project Title</th>
            <th class="circle--cell--right">Project Needs</th>
          </tr>
        </thead>
        <tbody>
          <tr class="clickable-row" data-href="project.html">
            <td>
              <h3>Invoice Delivery Tool</h3>
            </td>
            <td class="circle--cell--right">
              <span class="secondary-label">Rails Developer</span>
            </td>
          </tr>
          <tr class="clickable-row" data-href="project.html">
            <td>
              <h3>Twitter Client</h3>
            </td>
            <td class="circle--cell--right">
              <span class="secondary-label">Designer</span>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="grid-25 grid-push-5">

      <div class="circle--secondary--module">
        <div class="circle--primary--avatar">
          <a class="button">
            Upload Photo
            {{ form.image }}
          </a>
        </div>
      </div>

      <div class="circle--secondary--module">
        <h4>My Skills</h4>
        <ul class="circle--clone--list">
            {{ skill_formset.management_form }}
            {% for skill in skill_formset %}
                {{ skill.id }}
                <li class="skill_forms">
                    {{ skill.name }}
                    <a class="circle--clone--add">Add Skill</a>
                    <a class="circle--clone--remove">Remove</a>
                </li>
            {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock %}

team_builder/accounts/templates/accounts/signin.html
{% extends 'layout.html' %}

{% block title %}Sign In | {{ block.super }}{% endblock %}

{% block content %}
  <div class="bounds">
    <div class="grid-30 centered">
      <h2>Sign In</h2>
      <form method='POST'>
       {% csrf_token %}
       {{ form.as_p }}
       <input type='submit' value='Sign In' class='btn btn-default'>
      </form>
    </div>
  </div>
{% endblock %}

team_builder/accounts/templates/accounts/signup.html
{% extends 'layout.html' %}

{% block title %}Signup | {{ block.super }}{% endblock %}

{% block content %}
  <div class="bounds">
    <div class="grid-50 centered">
      <h2>Sign Up</h2>
      <form method='POST'>
       {% csrf_token %}
       {{ form.as_p }}
       <input type='submit' value='Signup' class='btn btn-default'>
      </form>
    </div>
  </div>
{% endblock %}