team_builder/accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('signin/', views.LoginView.as_view(), name='signin'),
    path('signout/', views.LogoutView.as_view(), name='signout'),
    path('<pk>/', views.profile_detail, name='profile'),
    path('<pk>/edit', views.profile_edit, name='edit'),
]

team_builder/projects/urls.py
from django.urls import path

from . import views

app_name='projects'

urlpatterns = [
	path('create/', views.create_project, name='create'),
	path('notification/', views.notification, name='notification'),
	path('application/', views.application_list, name='application'),
    path('application/<pk>/accept/', views.accept_application, name="accept"),
    path('application/<pk>/reject/', views.reject_application, name="reject"),
    path('application/accept/', views.accept_application_list, name="accept_application"),
    path('application/reject/', views.reject_application_list, name="reject_application"),
    path('application/new/', views.new_application_list, name="new_application"),
	path('<pk>/', views.project_detail, name='project'),
	path('edit/<pk>/', views.edit_project, name='edit'),
	path('<pk>/delete/', views.delete_project, name='delete'),
	path('<pk>/apply/<position_pk>', views.apply, name='apply'),
]

team_builder/team_builder/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import views


urlpatterns = [
	path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('projects/', include(('projects.urls', 'projects'), namespace='projects')),
    path('profile/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('search/', views.search_term, name='search'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

team_builder/projects/models.py
from django.conf import settings
from django.db import models


# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    timeline = models.CharField(max_length=255)
    requirements = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    

class Position(models.Model):
    ANDROID = "Android"
    DESIGN = "Design"
    JAVA = "Java"
    PHP = "PHP"
    PYTHON = "Python"
    RAILS = "Rails"
    WORDPRESS = "Wordpress"
    iOS = "iOS"
    SKILLS_CHOICE = (
        (ANDROID, "Android Developer"),
        (DESIGN, "Designer"),
        (JAVA, "Java Developer"),
        (PHP, "PHP Developer"),
        (PYTHON, "Python Developer"),
        (RAILS, "Rails Developer"),
        (WORDPRESS, "Wordpress Developer"),
        (iOS, "iOS Developer")
    )

    project = models.ForeignKey(
        Project,
        null=True,
        related_name="positions",
        on_delete=models.CASCADE)
    title = models.CharField(max_length=100, blank=True)
    description = models.TextField(max_length=500, blank=True)
    skill = models.CharField(
        max_length=20,
        choices=SKILLS_CHOICE,
        default="",
        blank=True)
    position_filled = models.BooleanField(default=False, blank=True)
    applicants = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through='Application')

    def __str__(self):
        return self.title


class Application(models.Model):
    applicant = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="application"
    )
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    status = models.CharField(max_length=20)

    def __str__(self):
        return "{}, {}".format(self.applicant, self.position)


class Notification(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="notification"
    )
    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    message = models.CharField(max_length=50)

    def __str__(self):
        return str(self.user)

team_builder/projects/forms.py
from django import forms
from . import models


class ProjectForm(forms.ModelForm):
    class Meta:
        model = models.Project
        fields = [
            "name",
            "description",
            "timeline",
            "requirements"
        ]


class PositionForm(forms.ModelForm):
    class Meta:
        model = models.Position
        fields = [
            "title",
            "description",
            "skill",
            "position_filled"
        ]


PositionFormSet = forms.modelformset_factory(
    models.Position,
    form=PositionForm,
)


PositionInlineFormSet = forms.inlineformset_factory(
    models.Project,
    models.Position,
    fields=('title', 'description', 'skill', 'position_filled', ),
    formset=PositionFormSet,
    can_delete=True,
    extra=2,
)

team_builder/projects/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from . import models
from . import forms

@login_required(login_url='accounts/signin/')
def project_detail(request, pk):
    '''Show project detail'''
    project = get_object_or_404(models.Project, pk=pk)
    positions = models.Position.objects.filter(project_id=pk)
    return render(request, 'projects/project.html', {
        'project': project,
        'positions': positions })


@login_required
def create_project(request):
    '''Create a new project and positions'''
    form = forms.ProjectForm()
    position_formset = forms.PositionInlineFormSet(
        queryset=models.Position.objects.none()
    )

    if request.method == 'POST':
        form = forms.ProjectForm(request.POST)
        position_formset = forms.PositionInlineFormSet(
            request.POST,
            queryset=models.Position.objects.none()
        )

        if form.is_valid() and position_formset.is_valid():
            project = form.save(commit=False)
            project.user = request.user
            project.save()
            position_instance = position_formset.save(commit=False)
            for obj in position_formset.deleted_objects:
                obj.delete()
            for position in position_instance:
                position.project = project
                position.save()
            return HttpResponseRedirect(reverse('home'))

    return render(request, 'projects/project_new.html', {
        'form': form,
        'position_formset': position_formset
        })


@login_required
def edit_project(request, pk):
    '''Update the project and positions'''
    try:
        project = models.Project.objects.get(pk=pk, user=request.user)
    except ObjectDoesNotExist:
        project = None

    form = forms.ProjectForm(instance=project)
    position_formset = forms.PositionInlineFormSet(
        queryset=models.Position.objects.filter(
            project_id=pk,
            project__user=request.user)
    )

    if request.method == 'POST':
        form = forms.ProjectForm(request.POST, instance=project)
        position_formset = forms.PositionInlineFormSet(
            request.POST,
            queryset=models.Position.objects.filter(
                project_id=pk,
                project__user=request.user)
        )

        if form.is_valid() and position_formset.is_valid():
            form.save()
            position_instance = position_formset.save(commit=False)
            for position in position_instance:
                position.project = project
                position.save()
            for position in position_formset.deleted_objects:
                position.delete()
            return HttpResponseRedirect(reverse("home"))

    return render(request, 'projects/project_edit.html', {
                'form': form,
                'position_formset': position_formset
            })


@login_required
def delete_project(request, pk):
    try:
        project = models.Project.objects.get(pk=pk, user=request.user)
    except ObjectDoesNotExist:
        project = None
    project.delete()
    return redirect('home')


@login_required
def apply(request, position_pk, pk):
    '''Applying for a position'''
    position = get_object_or_404(models.Position, pk=position_pk)
    try:
        models.Application.objects.get(
            applicant=request.user,
            position=position
        )
    except ObjectDoesNotExist:
        models.Application.objects.create(
            applicant=request.user,
            position=position,
            status="new"
        )
        messages.success(request, "You've applyed for {}!".format(position.title))
        return HttpResponseRedirect(reverse(
            'projects:project',
            kwargs={'pk': pk}))
    else:
        messages.warning(request, "You've already applyed for this position!")
        return HttpResponseRedirect(reverse(
            'projects:project',
            kwargs={'pk': pk}))


@login_required
def application_list(request):
    '''Show a list of all applications'''
    applications = models.Application.objects.filter(
            position__project__user=request.user)
    projects = models.Project.objects.filter(user=request.user)
    return render(request, 'accounts/applications.html', {
            'applications': applications,
            'projects': projects })


@login_required
def accept_application_list(request):
    '''Show a list of accepted applications'''
    applications = models.Application.objects.filter(
        status="accept",
        position__project__user=request.user)
    projects = models.Project.objects.filter(user=request.user)
    return render(request, 'accounts/applications.html', {
            'applications': applications,
            'projects': projects })


@login_required
def reject_application_list(request):
    '''Show a list of rejected applications'''
    applications = models.Application.objects.filter(
        status="reject",
        position__project__user=request.user)
    projects = models.Project.objects.filter(user=request.user)
    return render(request, 'accounts/applications.html', {
            'applications': applications,
            'projects': projects })


@login_required
def new_application_list(request):
    '''Show a list of new applied applications'''
    applications = models.Application.objects.filter(
        status="new",
        position__project__user=request.user)
    projects = models.Project.objects.filter(user=request.user)
    return render(request, 'accounts/applications.html', {
            'applications': applications,
            'projects': projects })


def accept_application(request, pk):
    '''Accept an application view'''
    application = get_object_or_404(models.Application, pk=pk)
    position = models.Position.objects.get(application__id=application.id)
    application.status = "accept"
    application.position.position_filled = True
    application.save()
    position.position_filled = True
    position.save()
    models.Notification.objects.create(
        user=application.applicant,
        application=application,
        message="Your application for {} is approved.".format(
                                                    application.position)
    )
    return redirect("projects:application")


def reject_application(request, pk):
    application = get_object_or_404(models.Application, pk=pk)
    application.status = "reject"
    application.save()
    models.Notification.objects.create(
        user=application.applicant,
        application=application,
        message="Your application for {} is rejected.".format(
                                                    application.position)
    )
    return redirect("projects:application")

def notification(request):
    try:
        notifications = models.Notification.objects.filter(user=request.user)
    except ObjectDoesNotExist:
        messages.warning(request, "There is no notification.")
    else:
        return render(request, "projects/notifications.html",
                    {'notifications': notifications })

team_builder/projects/templates/projects/layout.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>{% block title %}Circle{% endblock %}</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONTS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href={% static "css/global.css" %}>

  <!-- JS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
  <script type="text/javascript" src={% static "js/autogrow.js" %}></script>
  <script type="text/javascript" src={% static "js/global.js" %}></script>


</head>
<body>
  <header class="circle--header">
    <div class="bounds">
      <div class="circle--fluid">
        <div class="circle--fluid--cell">
          <h1 class="hide-text circle--logo"><a class="logo" href="{% url 'home' %}">Circle</a></h1>
        </div>
        <div class="circle--fluid--cell circle--fluid--primary">
          <div class="circle--search">
            <form action="{% url 'search' %}" method="GET">
              <input type='search' name='q'><button type='button' class='secondary small button'>
                <svg version="1.1" class="search" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 12 12" xml:space="preserve">
                  <path d="M12,10.6L8.3,6.9C8.7,6.2,9,5.4,9,4.5C9,2,7,0,4.5,0S0,2,0,4.5S2,9,4.5,9c0.9,0,1.7-0.3,2.4-0.7l3.7,3.7L12,10.6z M2,4.5
                  C2,3.1,3.1,2,4.5,2S7,3.1,7,4.5C7,5.9,5.9,7,4.5,7S2,5.9,2,4.5z"/>
                </svg>
            </form>
          </div>
        </div>
        <div class="circle--fluid--cell circle--fluid--secondary">
          <nav>
            <ul class="circle--inline">
              {% if user.is_authenticated %}
              <li><a href="{% url 'accounts:profile' user.id %}">{{ user.username }}</a></li>
              <li><a href="{% url 'accounts:signout' %}">Sign Out</a></li>
              {% else %}
              <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
              <li><a href="{% url 'accounts:signin' %}">Sign In</a></li>
              {% endif %}
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </header>
  </div>

{% block content %}
{% endblock %}
</body>
</html>

team_builder/projects/templates/projects/notifications.html
{% extends "accounts/layout.html" %}
{% load static from staticfiles %}

{% block content %}

<div class="bounds circle--page">
  <div class="circle--page--header grid-100">
    <h2>Notifications</h2>
    <ul>
      {% for notification in notifications %}
        <li>{{ notification.message }}</li>
      {% endfor %}
    </ul>
  </div>
</div>

{% endblock %}

team_builder/projects/templates/projects/project.html
{% extends 'projects/layout.html' %}
{% load static from staticfiles %}
{% load project_extras %}


{% block title %}{{ project.name }} | {{ block.super }}{% endblock %}


{% block content %}
  {% if project.user == request.user %}
  <div class="circle--actions--bar">
    <div class="bounds">
      <div class="grid-100">
        <a class="button" href="{% url 'projects:edit' project.id %}">Edit Project</a>
        <a class="button button-text" href="{% url 'projects:delete' project.id %}">Delete Project</a>
      </div>
    </div>
  </div>
  {% endif %}

  <div class="bounds circle--page circle--article">
    <div class="grid-70">
      <div class="circle--article--header">
        <h4 class="circle--article--section">Project</h4>
        <h1 class="circle--article--title">{{ project.name }}</h1>
        <p class="circle--article--byline">Project Owner: <a href="{% url 'accounts:profile' pk=project.user.id %}">{{ project.user.name }}</a></p>
      </div>

      <div class="circle--article--body">
        {{ project.description | markdown_to_html }}
      </div>

      <div class="circle--project--positions">
        <h2>Positions</h2>

        <ul class="circle--group--list">
          {% for position in positions %}
              <li>
                {% if position.title %}
                  <h3>{{ position.title }}</h3>
                {% endif %}
                {% if position.description %}
                  <p>{{ position.description | markdown_to_html }}</p>
                {% endif %}
                {% if project.user != request.user %}
                {% if position.position_filled == True %}
                  <a class="button button-primary button-inactive">Position Filled</a>
                {% elif request.user in position.applicants.all %}
                  <a class="button button-primary button-inactive">Applied</a>
                {% else %}
                  <a class="button button-primary" href="{% url 'projects:apply' pk=project.pk position_pk=position.pk %}">Apply</a>
                {% endif %}
              {% endif %}
            </li>
          {% endfor %}
        </ul>
      </div>

    </div>

    <div class="grid-25 grid-push-5">
      <div class="circle--secondary--module">
        <h3>Project Needs</h3>
        <ul class="circle--link--list">
          {% for position in positions %}
            <li><a>{{ position.skill }}</a></li>
          {% endfor %}
        </ul>
      </div>

      <div class="circle--secondary--module">
        <h3>Project Timeline</h3>
        <p>{{ project.timeline }}</p>
      </div>

      <div class="circle--secondary--module">
        <h3>Applicant Requirements</h3>
        <p>{{ project.requirements }}</p>
      </div>

    </div>
  </div>
  {% endblock %}

team_builder/projects/templates/projects/project_edit.html
{% extends 'projects/layout.html' %}

{% block content %}
<form method="POST" enctype="multipart/form-data">
  <div class="circle--actions--bar">
    <div class="bounds">
      <div class="grid-100">
        <input type="submit" value="Save Project" class="button button-primary">
        <a class="button button-text" href="{% url 'home' %}">Discard</a>
      </div>
    </div>
  </div>

  <div class="bounds circle--page circle--article">
    <div class="grid-70">
      <div class="circle--article--body">
        <div type="text" class="circle--input--h1" placeholder="Project Title">
          Project Title:
          {% csrf_token %}
          {{ form.name }}
        </div>
        <div>
          Desciption:
          {{ form.description }}
      </div>
      </div>

      <div class="circle--project--positions">
        <h2>Positions</h2>

        <ul class="circle--group--list circle--clone--list">
          {{ position_formset.management_form }}
          {% for position in position_formset %}
          {{ position.id }}
          <li>
            <p>Name:</p>
            {{ position.title }}
            <p>Description:</p>
            {{ position.description }}
            <p>Skill:</p>
            {{ position.skill }}
            <a class="circle--clone--add">Add Position</a>
            <a class="circle--clone--remove">Remove</a>
          </li>
          {% endfor %}
        </ul>
        <input type="submit" value="Save Project" class="button button-primary">

      </div>
    </div>

    <div class="grid-25 grid-push-5">

      <div class="circle--secondary--module">
        <h3>Project Timeline</h3>
        {{ form.timeline }}
      </div>

      <div class="circle--secondary--module">
        <h3>Applicant Requirements</h3>
        {{ form.requirements }}
      </div>

    </div>
  </div>
{% endblock %}

team_builder/projects/templates/projects/project_new.html
{% extends 'projects/layout.html' %}

{% block content %}
<form method="POST" enctype="multipart/form-data">
  <div class="circle--actions--bar">
    <div class="bounds">
      <div class="grid-100">
        <input type="submit" value="Save Project" class="button button-primary">
        <a class="button button-text" href="{% url 'home' %}">Discard</a>
      </div>
    </div>
  </div>

  <div class="bounds circle--page circle--article">
    <div class="grid-70">
      <div class="circle--article--body">
        <div type="text" class="circle--input--h1" placeholder="Project Title">
          Project Title:
          {% csrf_token %}
          {{ form.name }}
        </div>
        <div>
          Desciption:
          {{ form.description }}
      </div>
      </div>

      <div class="circle--project--positions">
        <h2>Positions</h2>

        <ul class="circle--group--list circle--clone--list">
          {{ position_formset.management_form }}
          {% for position in position_formset %}
          {{ position.id }}
          <li>
            <p>Name:</p>
            {{ position.title }}
            <p>Description:</p>
            {{ position.description }}
            <p>Skill:</p>
            {{ position.skill }}
            <a class="circle--clone--add">Add Position</a>
            <a class="circle--clone--remove">Remove</a>
          </li>
          {% endfor %}
        </ul>
        <input type="submit" value="Save Project" class="button button-primary">

      </div>
    </div>

    <div class="grid-25 grid-push-5">

      <div class="circle--secondary--module">
        <h3>Project Timeline</h3>
        {{ form.timeline }}
      </div>

      <div class="circle--secondary--module">
        <h3>Applicant Requirements</h3>
        {{ form.requirements }}
      </div>

    </div>
  </div>
{% endblock %}

team_builder/projects/templates/projects/search.html
<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>Circle &bull; Search</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONTS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href="css/global.css">

  <!-- JS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
  <script type="text/javascript" src="js/autogrow.js"></script>
  <script type="text/javascript" src="js/global.js"></script>


</head>
<body>
  <header class="circle--header">
    <div class="bounds">
      <div class="circle--fluid">
        <div class="circle--fluid--cell">
          <h1 class="hide-text circle--logo"><a class="logo" href="index.html">Circle</a></h1>
        </div>
        <div class="circle--fluid--cell circle--fluid--primary">
          <div class="circle--search">
            <input type="text" placeholder="Search Projects..." value="sass" />
            <button>
              <svg version="1.1" class="search" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 12 12" xml:space="preserve">
                <path d="M12,10.6L8.3,6.9C8.7,6.2,9,5.4,9,4.5C9,2,7,0,4.5,0S0,2,0,4.5S2,9,4.5,9c0.9,0,1.7-0.3,2.4-0.7l3.7,3.7L12,10.6z M2,4.5
                C2,3.1,3.1,2,4.5,2S7,3.1,7,4.5C7,5.9,5.9,7,4.5,7S2,5.9,2,4.5z"/>
              </svg>
            </button>
          </div>
        </div>
        <div class="circle--fluid--cell circle--fluid--secondary">
          <nav>
            <ul class="circle--inline">
              <li><a href="signup.html">Sign Up</a></li>
              <li><a href="signin.html">Sign In</a></li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </header>

  <div class="bounds circle--page">
    <div class="circle--page--header circle--fluid">
      <div class="circle--fluid--cell circle--fluid--primary">
        <h2>Search</h2>
        <p>Search research for: <span class="secondary-label">sass</span></p>
      </div>
      <div class="circle--fluid--cell circle--fluid--secondary">
        <a class="button button-primary icon-on-left" href="project_new.html">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 13 13" style="enable-background:new 0 0 13 13;" xml:space="preserve" class="add">
            <polygon points="7,6 7,0 6,0 6,6 0,6 0,7 6,7 6,13 7,13 7,7 13,7 13,6 "/>
          </svg>
          New Project
        </a>
      </div>
    </div>

    <div class="grid-25">
      <div class="circle--filter circle--secondary--module">
        <h4>Project Needs</h4>
        <ul class="circle--filter--list">
          <li><a class="selected">All Needs</a></li>
          <li><a>Android Developer</a></li>
          <li><a>Designer</a></li>
          <li><a>Java Developer</a></li>
          <li><a>PHP Developer</a></li>
          <li><a>Python Developer</a></li>
          <li><a>Rails Developer</a></li>
          <li><a>WordPress Developer</a></li>
          <li><a>iOS Developer</a></li>
        </ul>
      </div>
    </div>

    <div class="grid-70 grid-push-5">
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Project Title</th>
            <th class="circle--cell--right">Project Needs</th>
          </tr>
        </thead>
        <tbody>
          <tr class="clickable-row" data-href="project.html">
            <td>
              <h3>Invoice Delivery Tool</h3>
            </td>
            <td class="circle--cell--right">
              <span class="secondary-label">Rails Developer</span>
            </td>
          </tr>
          <tr class="clickable-row" data-href="project.html">
            <td>
              <h3>Twitter Client</h3>
            </td>
            <td class="circle--cell--right">
              <span class="secondary-label">Designer</span>
            </td>
          </tr>
        </tbody>
      </table>

    </div>

  </div>
</body>
</html>